SELECT DEPARTMENT_NAME AS "Nome do departamento",
    COUNT(e.EMPLOYEE_ID) AS "Quantidade de funcionarios"
FROM HR.DEPARTMENTS d
LEFT JOIN HR.EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME